
export LIBPNG_VERSION="1.6.16_cedar-14"
export NASM_VERSION="2.11.05"
export LIBJPEG_TURBO_VERSION="1.4.0_cedar-14"
export FREETYPE_VERSION="2.5.3_cedar-14"
export JPEG_ARCHIVE_VERSION="1.1.0_cedar-14"
export IMAGE_MAGICK_VERSION="6.8.9-5_Q16_cedar-14"
export REMOTE_PATH="imagemagick-${IMAGE_MAGICK_VERSION}.tgz"
export LIBPNG_REMOTE_PATH="libpng-${LIBPNG_VERSION}.tgz"
export NASM_REMOTE_PATH="nasm-${NASM_VERSION}.tgz"
export LIBJPEG_TURBO_REMOTE_PATH="libjpeg-turbo-${LIBJPEG_TURBO_VERSION}.tgz"
export FREETYPE_REMOTE_PATH="freetype-${FREETYPE_VERSION}.tgz"
export JPEG_ARCHIVE_REMOTE_PATH="jpeg-archive-${JPEG_ARCHIVE_VERSION}.tgz"
export S3_BUCKET="suzuri-buildpack-imagemagick"

